# Generated by Django 3.0.5 on 2020-06-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('division', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], default='Choose Your Blood Group', max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Select Gender', max_length=50)),
                ('height', models.CharField(max_length=4)),
                ('weight', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
