# Generated by Django 3.0.5 on 2020-06-15 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_auto_20200615_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
