# Generated by Django 3.0.5 on 2020-06-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0008_auto_20200616_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='img',
        ),
        migrations.AddField(
            model_name='donor',
            name='height',
            field=models.CharField(default='', max_length=4),
        ),
    ]
